config/routes.rb
Rails.application.routes.draw do
  resources :users do
    collection do
      get :count
    end
    member do
      get :name
    end
    resource :shop
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shop.rb
class Shop
  include Mongoid::Document

  belongs_to :user

  field :name, type: String
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Enum

  has_one :shop

  field :first_name, type: String
  field :last_name, type: String
  field :age, type: Integer
  field :gender, type: String
  field :address, type: Hash, default: {}
 

  validates_presence_of :first_name, :last_name, :age, :gender
  validates_numericality_of :age, :greater_than => 0

  enum :genders, [:male, :female, :others]

  def name
    first_name + ' ' + last_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_user
  before_action :set_shop, only: [:show, :edit, :update, :destroy]

  def show
  end

  def new
    @shop = Shop.new
  end

  def edit
  end

  def create
    @shop = Shop.new(shop_params)
    @shop.user_id = @user.id
    respond_to do |format|
      if @shop.save
        format.html { redirect_to @user, notice: "#{shop_params}" }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to @user, notice: 'Shop was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to @user, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_shop
      @shop = @user.shop
    end

    def set_user
      @user = User.find(params[:user_id])
    end

    def shop_params
      params.require(:shop).permit(:name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  rescue_from Mongoid::Errors::DocumentNotFound, with: :render_not_found
  before_action :set_user, only: [:show, :edit, :update, :destroy, :name]

  def index
    @users = User.all
  end

  def show
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @user.to_json, status: :ok }
    end
  end

  def new
    @user = User.new
  end

  def edit
    respond_to do |format|
      format.html { render :edit }
      format.json { render json: @user.to_json, status: :ok }
    end
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render nothing: true, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    head :no_content
  end

  def count
    @count = User.count

    render json: { count: @count }
  end

  def name
    render json: { name: @user.name }
  end

  def index
    @users = User.all
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @users.to_json, status: :ok }
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def render_not_found
    render json: { message: 'resource not found' }, status: :not_found
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :age, :gender, address: [:country, :address_1, :address_2])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blank</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body ng-app="userapp">
    <%= yield %>
  </body>
</html>

app/views/shops/_form.html.erb
<%= form_for @shop, :url => user_shop_path do |f| %>
  <% if @shop.errors.any? %>
    <% @shop.errors.full_messages.each do |message| %>
      <p><%= message %></p>
    <% end %>
  <% end %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shops/edit.html.erb
<h1>Shop Edit Page</h1>

<%= render 'form' %>

<%= link_to 'Shops Detail', user_shop_path(@user) %>
</br>
<%= link_to 'Back to user', @user %

app/views/shops/new.html.erb
<h1>New Shop</h1>

<%= render 'form' %>

<%= link_to 'Back to user', @user %>

app/views/shops/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Name:</strong>
  <%= @shop.name %>
</p>
<%= link_to 'Edit', edit_user_shop_path(@user) %>
</br>
<%= link_to 'Destroy', user_shop_path(@user), method: :delete %>
</br>
<%= link_to 'Back to user', @user %>

app/views/users/edit.html.erb
<div class="row" ng-controller="UserEditContoller" ng-init="init('<%= @user.id %>', 'edit')">
  <h1>User Edit Page</h1>

  <div user-form id="<%= @user.id %>"></div>

  <%= link_to 'Detail', @user %>
  <br/>
  <%= link_to 'Back', users_path %>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Users</h1>

<table ng-controller="UsersController as Users">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Age</th>
      <th>Gender</th>
    </tr>
  </thead>

  <tbody>
    <tr ng-repeat="user in users track by user._id.$oid">
      <td>{{user.first_name}}</td>
      <td>{{user.last_name}}</td>
      <td>{{user.age}}</td>
      <td>{{user.gender}}</td>
      <td><a ng-href="users/{{user._id.$oid}}">Detail</a></td>
      <td><button ng-click="displayEditForm(user)">Edit</button></td>
      <td><a href='' ng-click="deleteUser(user._id.$oid)" class="remove_user">Remove</a></td>
      <td><div id="{{user._id.$oid}}" user-form ng-if="show == user._id.$oid"></div></td>
    </tr>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="row" ng-controller="UserNewController" ng-init="init('create')">
  <h1>New User</h1>

  <div user-form></div>

  <%= link_to 'Back', users_path %>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <div id='first_name'>
    <%= @user.first_name %>
  </div>
</p>

<p>
  <strong>Last name:</strong>
  <div id='last_name'>
    <%= @user.last_name %>
  </div>
</p>

<p>
  <strong>Age:</strong>
  <div id='age'>
    <%= @user.age %>
  </div>
</p>
<p>
  <strong>Gender:</strong>
  <div id='gender'>
    <%= @user.gender %>
  </div>
</p>

<% if @user.address.present? %>
  <p>
    <strong>Country:</strong>
    <div id='country'>
      <%= @user.address[:country] %>
    </div>
  </p>
 
  <p>
    <strong>Address 1:</strong>
    <div id='address_1'>
      <%= @user.address[:address_1] %>
    </div>
  </p>

  <p>
    <strong>Address 2:</strong>
    <div id='address_2'>
      <%= @user.address[:address_2] %>
    </div>
  </p>
<% end %>

<% if @user.shop.present? %>
  <%= link_to 'Shop info', user_shop_path(@user) %>
<% else %>
  <%= link_to 'New Shop', new_user_shop_path(@user) %>
<% end %>

<br>

<%= link_to 'Edit', edit_user_path(@user) %>

<br>

<%= link_to 'Back', users_path %>